-- ============================================================================
-- NOTE: DEPRECATED - Triggers are no longer needed
-- ============================================================================
-- The application now handles user role initialization in code.
-- When a user logs in (via Google OAuth or email/password),
-- authService.ts automatically assigns them the default "user" role.
-- 
-- This approach is simpler and doesn't require database triggers.
-- All login logic is in: src/lib/authService.ts (getAuthenticatedSession)
--
-- NO ACTION NEEDED - just keep the code running in authService.ts
-- ============================================================================
